In [3]:
#matplotlib online
import matplotlib.pyplot as plt
import numpy as np

In [4]:
# np.dot is matrix product
x = np.array([1, 2])
y = np.array([-2, 1])
a = np.dot(x, y)
print(a)

0


In [5]:
# norm define is megnitude or length of vector
b = np.linalg.norm(x)
c = np.sqrt(x[0]**2 + x[1]**2)
# ** mean "to the power of" Ex.12**3 mean twelve to the power of third
print(b, c)

2.23606797749979 2.23606797749979


In [6]:
#result of np.arccos() is radian [In this case result is 1.5707963267948966 radian that equal is 90 degree]
theta = np.arccos(np.dot(x,y) / (np.linalg.norm(x) * np.linalg.norm(y)))
print(theta)

1.5707963267948966


In [7]:
# dtype = data-type, optional
B = np.array([[3,2,1], [2,6,5], [1,5,9]], dtype=float)
print(B)
print(B.T)
print(B - B.T)

[[3. 2. 1.]
 [2. 6. 5.]
 [1. 5. 9.]]
[[3. 2. 1.]
 [2. 6. 5.]
 [1. 5. 9.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# numpy.random.rand(d0, d1, ..., dn) = Random values in a given shape.
z = np.random.rand(3)
print(z)
j = np.dot(B, z)
print(j)
# @ is Python's Matrix Multiplication Operator
v = B @ z
print(v)
print(B.shape)
print(j.shape)
print(v.shape)
# difference between numpy and @ is link below
# https://stackoverflow.com/questions/34142485/difference-between-numpy-dot-and-python-3-5-matrix-multiplication

[0.19270719 0.16723976 0.80010521]
[1.71270631 5.389379   8.22985291]
[1.71270631 5.389379   8.22985291]
(3, 3)
(3,)
(3,)


In [9]:
print(z.T @ B @ z)

7.816117485806133


In [10]:
print(np.trace(B))
print(np.linalg.det(B))

18.0
65.00000000000004


In [11]:
# w, v = numpy.linalg.eig(a) is compute the eigenvalues and right eigenvectors of a square array
# https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html
# D = eigenvalues
# U = right eigenvectors
D, U = np.linalg.eig(B)
print(D)
print(U)

[13.11766327  3.44324229  1.43909444]
[[-0.19527095 -0.74608451  0.63657455]
 [-0.59990492 -0.42261825 -0.67934373]
 [-0.77587586  0.5145403   0.3650547 ]]


In [29]:
k1 = np.array([1.744, -1.861,1.0])
k2 = np.array([-1.45,-0.821,1.0])

print(U[:,0])
print(U[:,1])
print(np.dot(U[:,1], U[:,2]))
print(U@U.T)
print(B)
print(np.dot(k1, k2))

[-0.19527095 -0.59990492 -0.77587586]
[-0.74608451 -0.42261825  0.5145403 ]
1.1102230246251565e-16
[[ 1.00000000e+00 -1.11022302e-16 -8.32667268e-17]
 [-1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [-8.32667268e-17  0.00000000e+00  1.00000000e+00]]
[[3. 2. 1.]
 [2. 6. 5.]
 [1. 5. 9.]]
-0.0009190000000001142


In [34]:
B2 = np.array([[1,3], [3,2]], dtype=float)
D2, U2 = np.linalg.eig(B2)
print(D2)
print(U2)
print(U2[:,0])
print(U2[:,1])
print(np.dot(U2[:,0], U2[:,1]))
print(U2@U2.T)               

[-1.54138127  4.54138127]
[[-0.76301998 -0.6463749 ]
 [ 0.6463749  -0.76301998]]
[-0.76301998  0.6463749 ]
[-0.6463749  -0.76301998]
0.0
[[1. 0.]
 [0. 1.]]
